### ISSUE TITLE
Dialog overlays throw Uncaught TypeError

### ISSUE THREAD

**Issue by mattumotu** [trevorsaint/rural-payments-styleguide#9]
On the RPA guide for Dialog overlays clicking anywhere on the page throws the following error:

Uncaught TypeError: Cannot read property 'focus' of null
    at closeDialog (main.js:199)
    at HTMLDocument.click (main.js:239)
    at HTMLDocument.dispatch (jquery-1.11.0.js:3)
    at HTMLDocument.r.handle (jquery-1.11.0.js:3)

Browser: chrome  58.0.3029.110 
Page: http://rural-payments-styleguide.herokuapp.com/dialogs/
Repro: 
> Open page, 
> open dev tools (f12)
> click anywhere on the page
> observe bug

**Comment by mattumotu** [comment]
Similar in IE 11.
SCRIPT5007: Unable to get property 'focus' of undefined or null reference
File: dialogs, Line: 199, Column: 7

**Comment by trevorsaint** [comment]
Hello @mattumotu thanks for the bug notification. Unfortunately this project is no longer. I will not be updating anything on the RPA project, but thanks for the heads up :)
